In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Read catalogues and show columns

In [4]:
hunt = pd.read_csv('../data/hunt_catalogue.csv')
kharchenko = pd.read_csv('../data/kharchenko_catalogue.csv')
hunt_xm = pd.read_csv('../data/hunt_crossmatch.csv')

print(hunt.columns)
print(kharchenko.columns)
print(hunt_xm.columns)

FileNotFoundError: [Errno 2] No such file or directory: '../data/hunt_catalogue.csv'

### Show Hunt catalogue

In [ ]:
hunt

,recno,Name,ID,AllNames,Type,CST,N,CSTt,Nt,RA_ICRS,...,MOD16,MOD50,MOD84,minClSize,isMerged,isGMMMemb,NXmatches,XmatchType,_RA.icrs,_DE.icrs
0,1,1636-283,0,"1636-283,C1636-283,ESO_452-11,MWSC_2436",o,8.106141,38,8.794951,32,249.855743,...,13.771433,14.001991,14.187698,20,0,0,2,1:m,249.855750,-28.399165
1,2,ADS_16795,1,"ADS_16795,AR_Cas",o,6.832199,41,6.832199,41,352.592165,...,6.491674,6.649982,6.814627,40,0,0,1,1:1,352.592006,58.553401
2,3,AH03_J0748+26.9,2,"AH03_J0748+26.9,AH03_J0748-26.9,AH03_J0748_26....",o,11.585524,68,11.781309,66,117.155887,...,13.326923,13.521471,13.707494,10,0,0,2,1:m,117.155899,-26.972694
3,4,ASCC_5,3,"ASCC_5,MWSC_93",o,8.316422,25,8.316422,25,14.469082,...,11.046813,11.212086,11.370137,10,0,0,1,1:1,14.469101,55.829182
4,5,ASCC_6,4,"ASCC_6,MWSC_141,Theia_2326",o,19.258570,209,19.258570,209,26.842159,...,10.703223,10.890650,11.055896,80,0,0,2,1:m,26.842166,57.738606
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7162,7163,vdBergh_85,7162,vdBergh_85,o,11.847597,105,11.847597,105,101.720134,...,10.931759,11.125109,11.264691,80,0,0,1,1:1,101.720138,1.324254
7163,7164,vdBergh_92,7163,vdBergh_92,o,21.995554,345,21.995554,345,106.036502,...,10.040602,10.191625,10.338547,40,0,0,1,m:1,106.036522,-11.442345
7164,7165,vdBergh_113,7164,"UBC_1005,UFMG_84,vdBergh_113",o,15.770199,163,15.829355,152,272.165492,...,10.599004,10.748435,10.885481,80,0,0,3,1:m,272.165496,-21.441471
7165,7166,vdBergh_130,7165,vdBergh_130,o,11.430369,162,12.842494,131,304.517447,...,10.996379,11.143586,11.296269,80,0,0,1,1:1,304.517467,39.366669
7166,7167,vdBergh_152,7166,"OCSN_37,PTB_3,vdBergh_152",o,7.825618,25,7.825618,25,333.362827,...,7.602933,7.762949,7.912142,20,0,0,3,1:m,333.362758,70.176287

## Show catalogues available in Hunt's crossmatch table

In [ ]:
set(hunt_xm['SourceCat'])

{'Anders+22',
 'Bastian+19',
 'Bica+08',
 'Bica+18',
 'Cantat-Gaudin+20',
 'Casado+21',
 'Casado+23',
 'Castro-Ginard+20',
 'Castro-Ginard+22',
 'Chi+22',
 'Chi+23',
 'Dias+02',
 'Ferreira+19',
 'Ferreira+20',
 'Ferreira+21',
 'Hao+20',
 'Hao+22',
 'He+21',
 'He+22a',
 'He+22b',
 'He+22c',
 'Hunt+21',
 'Jaehnig+21',
 'Kharchenko+13',
 'Kounkel+20',
 'Li+22',
 'Li+23',
 'Liu+19',
 'Qin+20',
 'Qin+23',
 'Santos-Silva+21',
 'Sim+19',
 'Tian+20',
 'Vasiliev+21',
 'Zari+18'}

### Get only the objects crossmatched to Kharchenko's catalogue

In [ ]:
kharchenko_xm = hunt_xm.query('SourceCat == "Kharchenko+13"')
kharchenko_xm

,recno,ID,NameLit,SourceCat,TypeSourceCat,Sep,SepTidal,SepTidalLit,SepTidalData,pmRASep,pmRASigma,pmDESep,pmDESigma,PlxSep,PlxSigma,maxSigma,meanSigma
0,1,0,1636-283,Kharchenko+13,hipparcos,0.000298,0.002366,0.003970,0.002366,3.4450,0.662721,1.696,0.3213,0.04456,0.0000,0.663,0.3280
1,2,0,1636-283,Kharchenko+13,position,0.000298,0.002366,0.003970,0.002366,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,0,2MASS-GC02,Kharchenko+13,"position,hipparcos",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,11,0,AH03_J0822+36.4,Kharchenko+13,"position,hipparcos",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,25,0,ASCC_1,Kharchenko+13,"position,hipparcos",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29937,29938,7161,vdBergh_83,Kharchenko+13,position,0.114700,0.154470,0.955673,0.154470,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29938,29939,7162,vdBergh_85,Kharchenko+13,hipparcos,0.009891,0.024375,0.076088,0.024375,0.2275,0.043188,1.905,0.4513,0.06676,0.2839,0.451,0.2595
29940,29941,7162,vdBergh_85,Kharchenko+13,position,0.009891,0.024375,0.076088,0.024375,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29942,29943,7163,vdBergh_92,Kharchenko+13,position,0.089140,0.185433,0.356566,0.185433,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29944,29945,3217,vdBergh_92,Kharchenko+13,position,0.149400,0.210250,0.597759,0.210250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Get rid of the not crossmatched objects (Sep = Nan)

In [ ]:
kharchenko_xm = kharchenko_xm.dropna(subset = ['Sep'])
kharchenko_xm

,recno,ID,NameLit,SourceCat,TypeSourceCat,Sep,SepTidal,SepTidalLit,SepTidalData,pmRASep,pmRASigma,pmDESep,pmDESigma,PlxSep,PlxSigma,maxSigma,meanSigma
0,1,0,1636-283,Kharchenko+13,hipparcos,0.000298,0.002366,0.003970,0.002366,3.4450,0.662721,1.6960,0.32130,0.04456,0.0000,0.663,0.3280
1,2,0,1636-283,Kharchenko+13,position,0.000298,0.002366,0.003970,0.002366,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,27,114,ASCC_10,Kharchenko+13,hipparcos,0.164400,0.031312,0.310144,0.031312,1.0470,0.274158,0.2413,0.05259,0.11460,0.4058,0.406,0.2442
28,29,114,ASCC_10,Kharchenko+13,position,0.164400,0.031312,0.310144,0.031312,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,30,50,ASCC_100,Kharchenko+13,position,0.025990,0.008916,0.071212,0.008916,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29937,29938,7161,vdBergh_83,Kharchenko+13,position,0.114700,0.154470,0.955673,0.154470,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29938,29939,7162,vdBergh_85,Kharchenko+13,hipparcos,0.009891,0.024375,0.076088,0.024375,0.2275,0.043188,1.9050,0.45130,0.06676,0.2839,0.451,0.2595
29940,29941,7162,vdBergh_85,Kharchenko+13,position,0.009891,0.024375,0.076088,0.024375,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29942,29943,7163,vdBergh_92,Kharchenko+13,position,0.089140,0.185433,0.356566,0.185433,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29944,29945,3217,vdBergh_92,Kharchenko+13,position,0.149400,0.210250,0.597759,0.210250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Show how many unique clusters in Hunt are crossmatched (unique ID)

In [ ]:
len(np.unique(kharchenko_xm['ID']))

1705

### Count how many of these belong to the right type ('o')

In [ ]:
c = 0

for i in np.unique(kharchenko_xm['ID'])[1:2]:
    if i > 7166: continue
    type_object = hunt.query('ID == @i')['Type'][hunt.query('ID == @i').index[0]]
    if type_object == 'o': c = c + 1

print(c)

1

### Count how many of these belong to the right type in Kharchenko's catalogue (not 'g' -> globular cluster)

In [ ]:
kharchenko_names_oc = np.array(kharchenko.query('Type != "g"')['Name'],dtype = object)

In [ ]:
c = 0

for i in np.unique(kharchenko_xm['ID']):
    if i > 7166: continue
    type_object = hunt.query('ID == @i')['Type'][hunt.query('ID == @i').index[0]]
    if type_object == 'o': 
        for j in np.unique(kharchenko_xm.query('ID == @i')['NameLit'])[0:1]:
            if j in kharchenko_names_oc:
                c = c + 1

print(c)

1485

### It can still be that the name we were checking was in the allNames column, check this

In [ ]:
c = 0
cc = 0

for i in np.unique(kharchenko_xm['ID']):
    if i > 7166: continue
    type_object = hunt.query('ID == @i')['Type'][hunt.query('ID == @i').index[0]]
    if type_object == 'o': 
        if hunt.query('ID == @i')['AllNames'].isnull().values[0]: continue
        for j in list(hunt.query('ID == @i')['AllNames'])[0].split(','):
            if j in kharchenko_names_oc:
                c = c + 1

print(c)

1513