In [78]:
# from astropy.io import fits
import numpy as np
import matplotlib.pyplot as plt
from astropy.io import fits
from matplotlib.ticker import (MultipleLocator, AutoMinorLocator)
import pandas as pd

hunt = pd.read_csv('Data\\Hunt\\huntfile.csv')
khar = pd.read_csv('Data\\Kharchenko\\kharchenkofile.csv')
dias = pd.read_csv('Data\\Dias\\diasfile.csv')
xmatch = pd.read_csv('Data\\Hunt\\xmatchfile.csv')

#replace the space by an underscore
dias['Cluster'] = dias['Cluster'].str.replace(' ', '_')
dias

,Cluster,RAh,RAm,RAs,DE-,DEd,DEm,DEs,Class,Diam,...,Nc,r_pmRA,RV,e_RV,o_RV,r_RV,[Fe/H],e_[Fe/H],o_[Fe/H],TrType
0,Berkeley_58,0,0,12,+,60,58,0,NaN,11.0,...,88,K14,-87.00,1.78,1,D14,NaN,NaN,0,NaN
1,NGC_7801,0,0,21,+,50,44,30,r,8.0,...,85,D14,NaN,NaN,0,NaN,NaN,NaN,0,4-3-p-*
2,FSR_0459,0,0,39,+,59,14,20,IR,2.0,...,8,K12,NaN,NaN,0,NaN,NaN,NaN,0,NaN
3,Stock_18,0,1,37,+,64,37,30,NaN,6.0,...,109,D14,NaN,NaN,0,NaN,NaN,NaN,0,4-2-p-*
4,Berkeley_59,0,2,14,+,67,25,0,NaN,10.0,...,2,BDW,-5.17,9.48,3,D14,NaN,NaN,0,3-3-m-n
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2162,Frolov_1,23,57,24,+,61,38,0,nf,4.0,...,65,D14,16.40,3.00,1,K12,NaN,NaN,0,NaN
2163,NGC_7790,23,58,24,+,61,12,30,NaN,5.0,...,1,BDW,-77.48,0.13,1,MMU,NaN,NaN,0,NaN
2164,NGC_7795,23,58,37,+,60,2,6,NaN,21.0,...,878,D14,NaN,NaN,0,NaN,NaN,NaN,0,NaN
2165,FSR_0460,23,59,10,+,60,41,31,IR,1.4,...,38,D14,NaN,NaN,0,NaN,NaN,NaN,0,NaN
2166,NGC_7762,23,59,56,+,68,2,3,NaN,4.4,...,24,D14,NaN,NaN,0,NaN,NaN,NaN,0,NaN

In [79]:
#crossmatch
dias_xm = xmatch.query('SourceCat == "Dias+02"').dropna(subset=['Sep']) #Get crossmatch table with seperation=NaN removed

dias_xm

,ID,NameLit,SourceCat,TypeSourceCat,Sep,SepTidal,SepTidalLit,SepTidalData,pmRASep,pmRASigma,pmDESep,pmDESigma,PlxSep,PlxSigma,maxSigma,meanSigma
8,2,AH03_J0748+26.9,Dias+02,position,0.02773,0.189541,0.831918,0.189541,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,50,ASCC_100,Dias+02,position,0.03096,0.010619,0.099860,0.010619,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,51,ASCC_101,Dias+02,position,0.05648,0.018600,0.156883,0.018600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,2145,ASCC_104,Dias+02,position,0.15070,0.302126,0.313899,0.302126,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,52,ASCC_104,Dias+02,position,0.07506,0.051464,0.156374,0.051464,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29924,7164,vdBergh_113,Dias+02,position,0.02870,0.062091,0.245980,0.062091,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29930,7166,vdBergh_152,Dias+02,position,0.07382,0.104022,0.354355,0.104022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29932,7160,vdBergh_80,Dias+02,position,0.03122,0.029089,0.312177,0.029089,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29936,7161,vdBergh_83,Dias+02,position,0.13490,0.181712,0.647546,0.181712,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29941,7162,vdBergh_85,Dias+02,position,0.01030,0.025379,0.308965,0.025379,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [80]:
#remove duplicates
dias_xmnodup = dias_xm.drop_duplicates(subset=['ID'], inplace=False) 
dias_xmnodup

,ID,NameLit,SourceCat,TypeSourceCat,Sep,SepTidal,SepTidalLit,SepTidalData,pmRASep,pmRASigma,pmDESep,pmDESigma,PlxSep,PlxSigma,maxSigma,meanSigma
8,2,AH03_J0748+26.9,Dias+02,position,0.02773,0.189541,0.831918,0.189541,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,50,ASCC_100,Dias+02,position,0.03096,0.010619,0.099860,0.010619,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,51,ASCC_101,Dias+02,position,0.05648,0.018600,0.156883,0.018600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,2145,ASCC_104,Dias+02,position,0.15070,0.302126,0.313899,0.302126,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,52,ASCC_104,Dias+02,position,0.07506,0.051464,0.156374,0.051464,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29924,7164,vdBergh_113,Dias+02,position,0.02870,0.062091,0.245980,0.062091,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29930,7166,vdBergh_152,Dias+02,position,0.07382,0.104022,0.354355,0.104022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29932,7160,vdBergh_80,Dias+02,position,0.03122,0.029089,0.312177,0.029089,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29936,7161,vdBergh_83,Dias+02,position,0.13490,0.181712,0.647546,0.181712,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29941,7162,vdBergh_85,Dias+02,position,0.01030,0.025379,0.308965,0.025379,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [81]:
#sort out globular clusters in hunt file
hunt_oc = hunt.loc[hunt['Type'] == 'o']

In [82]:
#merge
diashunt = pd.merge(dias_xmnodup, hunt_oc, on= 'ID', how='inner')
diashunt

,ID,NameLit,SourceCat,TypeSourceCat,Sep,SepTidal,SepTidalLit,SepTidalData,pmRASep,pmRASigma,...,diffAV50,diffAV84,MOD16,MOD50,MOD84,minClSize,isMerged,isGMMMemb,NXmatches,XmatchType
0,2,AH03_J0748+26.9,Dias+02,position,0.02773,0.189541,0.831918,0.189541,NaN,NaN,...,1.079003,1.455453,13.326923,13.521471,13.707494,10,0,0,2,1:m
1,50,ASCC_100,Dias+02,position,0.03096,0.010619,0.099860,0.010619,NaN,NaN,...,0.658193,0.981117,7.588992,7.742329,7.899593,20,0,0,1,1:1
2,51,ASCC_101,Dias+02,position,0.05648,0.018600,0.156883,0.018600,NaN,NaN,...,0.381515,0.556617,7.770802,7.926659,8.100071,80,0,0,2,1:m
3,2145,ASCC_104,Dias+02,position,0.15070,0.302126,0.313899,0.302126,NaN,NaN,...,1.317957,1.621533,9.605561,9.738195,9.895556,40,0,0,1,m:1
4,52,ASCC_104,Dias+02,position,0.07506,0.051464,0.156374,0.051464,NaN,NaN,...,0.370198,0.578004,7.812606,7.998246,8.150210,20,0,0,1,m:1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1216,7164,vdBergh_113,Dias+02,position,0.02870,0.062091,0.245980,0.062091,NaN,NaN,...,2.649548,2.985685,10.599004,10.748435,10.885481,80,0,0,3,1:m
1217,7166,vdBergh_152,Dias+02,position,0.07382,0.104022,0.354355,0.104022,NaN,NaN,...,0.700407,0.966768,7.602933,7.762949,7.912142,20,0,0,3,1:m
1218,7160,vdBergh_80,Dias+02,position,0.03122,0.029089,0.312177,0.029089,NaN,NaN,...,2.555333,2.900121,9.749496,9.897707,10.063605,20,0,0,1,1:1
1219,7161,vdBergh_83,Dias+02,position,0.13490,0.181712,0.647546,0.181712,NaN,NaN,...,1.345328,1.846767,9.630401,9.778452,9.981219,80,0,0,1,1:1
1220,7162,vdBergh_85,Dias+02,position,0.01030,0.025379,0.308965,0.025379,NaN,NaN,...,2.159117,2.505461,10.931759,11.125109,11.264691,80,0,0,1,1:1

In [91]:
#merge on names
dias_expanded = diashunt.assign(synonym=diashunt['AllNames'].str.split(',')).explode('synonym')
allnamemerge = pd.merge(dias_expanded, dias, left_on= 'synonym', right_on='Cluster', how='inner' )

allnamenodup = allnamemerge.drop_duplicates(subset=['synonym'], inplace=False) 
allnamenodup

,ID,NameLit,SourceCat,TypeSourceCat,Sep,SepTidal,SepTidalLit,SepTidalData,pmRASep,pmRASigma,...,Nc,r_pmRA,RV_y,e_RV_y,o_RV,r_RV,[Fe/H],e_[Fe/H],o_[Fe/H],TrType
0,2,AH03_J0748+26.9,Dias+02,position,0.02773,0.189541,0.831918,0.189541,NaN,NaN,...,78,D14,NaN,NaN,0,NaN,-0.100,0.12,0,NaN
1,2,AH03_J0748+26.9,Dias+02,position,0.02773,0.189541,0.831918,0.189541,NaN,NaN,...,45,K14,NaN,NaN,0,NaN,NaN,NaN,0,NaN
2,50,ASCC_100,Dias+02,position,0.03096,0.010619,0.099860,0.010619,NaN,NaN,...,11,K05,-25.96,0.37,3,D14,NaN,NaN,0,NaN
3,51,ASCC_101,Dias+02,position,0.05648,0.018600,0.156883,0.018600,NaN,NaN,...,12,K05,-32.00,2.10,1,D14,NaN,NaN,0,NaN
4,52,ASCC_104,Dias+02,position,0.07506,0.051464,0.156374,0.051464,NaN,NaN,...,22,K05,-6.68,4.21,3,D14,NaN,NaN,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1239,7164,vdBergh_113,Dias+02,position,0.02870,0.062091,0.245980,0.062091,NaN,NaN,...,1023,D14,-16.00,3.70,1,D14,-0.358,0.09,1,3-3-p-n
1240,7166,vdBergh_152,Dias+02,position,0.07382,0.104022,0.354355,0.104022,NaN,NaN,...,297,D14,-41.00,0.90,1,D14,NaN,NaN,0,3-3-p-n
1241,7160,vdBergh_80,Dias+02,position,0.03122,0.029089,0.312177,0.029089,NaN,NaN,...,28,D14,NaN,NaN,0,NaN,NaN,NaN,0,1-2-p-n
1242,7161,vdBergh_83,Dias+02,position,0.13490,0.181712,0.647546,0.181712,NaN,NaN,...,302,D14,NaN,NaN,0,NaN,NaN,NaN,0,3-2-p-n
1243,7162,vdBergh_85,Dias+02,position,0.01030,0.025379,0.308965,0.025379,NaN,NaN,...,39,D14,NaN,NaN,0,NaN,NaN,NaN,0,1-2-p-*